development:
  adapter: mysql2
  database: NABAL_dev
  username: semin
  password: semin
  host: 192.168.1.2
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: NABAL
  username: semin
  password: semin
  host: 192.168.1.2
  pool: 5
  timeout: 5000
